# Hello World! 

This is my first program using jupyter notebook!

In [1]:
print('Hello World!')

Hello World!


In [2]:
print("Hello World!")

Hello World!


$a+b=42$

using $ to use lattic to express math equation

In [3]:
4+5

9

In [4]:
85^3

86

In [5]:
86*3

258

# Variables

In [6]:
x = 3

In [10]:
%whos
#this tells you the memories used in the program

Variable   Type    Data/Info
----------------------------
x          int     3


In [11]:
print(type(x))

<class 'int'>


In [12]:
x=6.66

In [13]:
%whos

Variable   Type     Data/Info
-----------------------------
x          float    6.66


In [14]:
print(type(x))

<class 'float'>


In [15]:
y=5

In [16]:
z=x*y

In [17]:
%whos

Variable   Type     Data/Info
-----------------------------
x          float    6.66
y          int      5
z          float    33.3


In [18]:
a,b,c,d = 1,0.5,-3,4.0

In [19]:
%whos

Variable   Type     Data/Info
-----------------------------
a          int      1
b          float    0.5
c          int      -3
d          float    4.0
x          float    6.66
y          int      5
z          float    33.3


In [20]:
del b

In [21]:
print(a,b,c,d)

NameError: name 'b' is not defined

In [22]:
print(a,c,d)

1 -3 4.0


In [23]:
a=2+4j

In [24]:
b=3-5j

In [25]:
c=a+b

In [26]:
c

(5-1j)

In [27]:
type(c)

complex

In [28]:
d='Hello World!'

In [29]:
type(d)

str

# Operators

In [30]:
1+3 #addition

4

In [31]:
3-2 #substraction

1

In [32]:
9/3 #division

3.0

In [33]:
3*3 #multiplication

9

In [34]:
10%3 #reminder

1

In [35]:
10//3 #floor division

3

In [36]:
4**2 # to the power of 

16

In [37]:
_ #underscore contains the last results that has been stored in a variable

16

# Bool Type

In [38]:
1 == 1

True

In [39]:
2 >= 1

True

In [40]:
2 > 3

False

In [41]:
4 != 6

True

In [42]:
type(True)

bool

In [43]:
type(False)

bool

In [1]:
a=True
b=True
c=False

In [2]:
%whos

Variable   Type    Data/Info
----------------------------
a          bool    True
b          bool    True
c          bool    False


In [3]:
a and b
a and c
b and c

False

In [4]:
print(a and b)
print(a and c)
Print(b and c)

True
False


NameError: name 'Print' is not defined

In [5]:
print(a and b)
print(a and c)
print(b and c)

True
False
False


In [6]:
print(a or b)
print(a or c)
print(c or b)

True
True
True


In [7]:
not(a)

False

In [8]:
not(c)

True

In [9]:
not(a and b)

False

In [10]:
print((not(2!=3) and True) or (True and False) )

False


In [11]:
divmod(27,5)

(5, 2)

# Some Useful Functions

In [12]:
round(4.5)

4

In [13]:
round(4.51)

5

In [14]:
round(4.55555,3)

4.556

In [15]:
divmod(27,5)

(5, 2)

In [16]:
divmod(28,4)

(7, 0)

In [17]:
type(divmod(28,4))

tuple

In [18]:
g = divmod(15,4)

In [19]:
g[0]

3

In [20]:
g[1]

3

In [21]:
print(isinstance(1,int))

True


In [22]:
print(isinstance(1.0,int))

False


In [23]:
print(isinstance(1.0,(int,float))

SyntaxError: unexpected EOF while parsing (<ipython-input-23-da91f0096613>, line 1)

In [24]:
print(isinstance(1.0,(int,float)))

True


In [25]:
pow(3,2)

9

In [26]:
pow(3,2,2) #equals 3^2%2

1

In [27]:
a = int(input('Please enter an integar: '))

Please enter an integar: 5


In [28]:
type(a)

int

In [29]:
b = input('Please enter an integar: ')

Please enter an integar: 6


In [30]:
type(b)

str

In [31]:
print? # add a ? after a func will display how to use it 

In [32]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



# Functions

In [1]:
def sampleFunc(a=0)
    return a

SyntaxError: invalid syntax (<ipython-input-1-acc3c41c773b>, line 1)

In [14]:
def sampleFunc(a=0): # sets a default 
    return a

In [15]:
sampleFunc()

0

In [16]:
sampleFunc(1)

1

In [5]:
def sampleFunc2(*a): # this allows multiple inputs
    sum = 0
    for i in range(len(a)):
        sum += a[i]
    return sum

In [6]:
sampleFunc2(2,3,4)

9

In [7]:
sampleFunc2(2,3,4,5,6,7)

27

In [9]:
sampleFunc2(8)

8

In [8]:
sampleFunc2(2,3.7,4.0)

9.7

In [12]:
def printVV(**a): #this allows to print all the keys and values
    for i in a:
        print('Variable is ',i,', and the value is ',a[i])


In [13]:
printVV(a=4,b='N',c=4.6,d=2+3j)

Variable is  a , and the value is  4
Variable is  b , and the value is  N
Variable is  c , and the value is  4.6
Variable is  d , and the value is  (2+3j)


In [17]:
def printList(L=[1,2,3]):
    print(L)

In [18]:
printList()

[1, 2, 3]


In [19]:
L2=[0,9,4,6,-12]
printList(L2)

[0, 9, 4, 6, -12]


In [20]:
printList(L3=[4,5,6])

TypeError: printList() got an unexpected keyword argument 'L3'

In [21]:
printList(L=[4,5,6])

[4, 5, 6]


In [22]:
help(printList())

[1, 2, 3]
Help on NoneType object:

class NoneType(object)
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __repr__(self, /)
 |      Return repr(self).
 |  
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.



# Modules

In [1]:
import sys
sys.path.append('/Users/yuanni/Documents/Python/myModules/')
# add Modules folder to the path

In [2]:
import MyUniversalFunctions as myfs
#import modules and name them

In [3]:
myfs.addAllNumerics?

In [4]:
myfs.addAllNumerics(1,3,5,7,9)

25

In [5]:
help(myfs.addAllNumerics)

Help on function addAllNumerics in module MyUniversalFunctions:

addAllNumerics(*args)



In [6]:
from MyUniversalFunctions import addAllNumerics

In [7]:
addAllNumerics(2,3,4,6,8)

23

In [8]:
def swapValues(L,idx1,idx2):
    tmp = L[idx1]
    L[idx1] = L[idx2]
    L[idx2] = tmp
    return L

In [9]:
L = [2,3,6,7]

In [10]:
L2 = swapValues(L,1,3)

In [11]:
print(L2)

[2, 7, 6, 3]


In [14]:
myfs.sortList(L)

[2, 3, 6, 7]

In [15]:
help(myfs.sortList)

Help on function sortList in module MyUniversalFunctions:

sortList(L)



In [16]:
a = 'string'

In [21]:
b=a.capitalize()

In [23]:
b

'String'

In [24]:
c=a.replace('i','3')

In [25]:
c

'str3ng'

# Data Structure

In [2]:
pip install jupyterthemes

Note: you may need to restart the kernel to use updated packages.


In [3]:
jt -l

NameError: name 'jt' is not defined

In [1]:
L = [1,3,5,7] # list
T = (1,3,5,7) # tuple
S = {1,3,5,7} # set
D = {1:'one',3:'three',5:'five',7:'seven'} # dictionary

In [2]:
print(type(L))
print(type(T))
print(type(S))
print(type(D))

<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'dict'>


In [3]:
L[1]

3

In [4]:
T(1)

TypeError: 'tuple' object is not callable

In [5]:
T[1]

3

In [6]:
print(L[2])
print(T[2])
print(5 in S)
print(D[5])

5
5
True
five


In [7]:
D1 = {2:'two',4:'four',6:'six',8:'eight'}

In [8]:
D2 = D1+D2

NameError: name 'D2' is not defined

In [9]:
D2 = D.update(D1)

In [10]:
D2

In [11]:
D

{1: 'one',
 3: 'three',
 5: 'five',
 7: 'seven',
 2: 'two',
 4: 'four',
 6: 'six',
 8: 'eight'}

In [12]:
D.sort()

AttributeError: 'dict' object has no attribute 'sort'

In [13]:
D.keys()

dict_keys([1, 3, 5, 7, 2, 4, 6, 8])

In [14]:
L

[1, 3, 5, 7]

In [15]:
L1 = L

In [16]:
L1

[1, 3, 5, 7]

In [17]:
L1[1]=4

In [18]:
L1 # L and L1 reference to the same memory

[1, 4, 5, 7]

In [19]:
L

[1, 4, 5, 7]

In [20]:
L2 = L.copy() 
# L2 and L reference to different memory using .copy()

In [21]:
L2

[1, 4, 5, 7]

In [22]:
L2[1] = 3

In [23]:
L2

[1, 3, 5, 7]

In [24]:
L

[1, 4, 5, 7]

In [25]:
# slicing a list returns a copy (Numpy is different)

In [26]:
L3 = [x**2 for x in range(10)]

In [27]:
L3

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# Numpy

In [3]:
'''Why Numpy? Numpy is Faster''' 

'Why Numpy? Numpy is Faster'

In [3]:
import numpy as np

In [5]:
a = np.array([1,2,3,4,5])
b = np.array((1,6,3,4,9))

In [6]:
print(a,b)

[1 2 3 4 5] [1 6 3 4 9]


In [7]:
print(a)

[1 2 3 4 5]


In [8]:
print(b)

[1 6 3 4 9]


In [9]:
type(a)

numpy.ndarray

In [10]:
type(b)

numpy.ndarray

In [12]:
a.dtype

dtype('int64')

In [13]:
c = np.array([1,3,5,7],dtype='f')

In [14]:
c

array([1., 3., 5., 7.], dtype=float32)

In [16]:
c.dtype # data type

dtype('float32')

In [18]:
a = np.array([[1,2,3],[4,5,6]])

In [19]:
print(a.ndim) # dim stands for dimension

2


In [20]:
a[1]

array([4, 5, 6])

In [21]:
a[0]

array([1, 2, 3])

In [22]:
b = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [23]:
print(b.ndim)

3


In [24]:
print(b.shape[0],b.shape[1],b.shape[2])

2 2 3


In [25]:
print(b[1,0,2])

3


In [1]:
'''
np.arange
np.random.permutation
np.reshape
'''

'\nnp.arrange\nnp.random.permutation\nnp.reshape\n'

In [4]:
A = np.arange(100)

In [5]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [7]:
B = np.arange(20,100)

In [8]:
print(B)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]


In [9]:
C = np.arange(20,100,3) # (start, end, step)

In [10]:
print(C)

[20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74 77 80 83 86 89
 92 95 98]


In [11]:
A = np.random.permutation(np.arange(10))

In [12]:
print(A)

[7 3 6 1 4 2 9 8 0 5]


In [13]:
V = np.random.randint(0,10)

In [14]:
print(V)

7


In [15]:
np.random.randint(0,10)

6

In [16]:
np.random.randint(0,10)

2